### ISSUE TITLE
about test setting

### ISSUE THREAD

**Issue by nhw649** [bytedance/fc-clip#26]
Why do I get an error when I use the following settings?
```
TEST:
      SEMANTIC_ON: False
      INSTANCE_ON: False
      PANOPTIC_ON: True
```
![QQ截图20240317140523](https://github.com/bytedance/fc-clip/assets/67191596/e11802aa-5687-448d-b6d9-7bf1562230db)
